[build]
  # Directory to publish from the frontend build
  publish = "packages/frontend/out"
  
  # Default build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

# Function configuration - updated path
[functions]
  directory = "packages/backend/netlify/functions"

# Redirects for SPA routing
[[redirects]]
  from = "/scan"
  to = "/.netlify/functions/scan"
  status = 200

# For Next.js static export
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle trailing slashes for Next.js
[[redirects]]
  from = "/*/"
  to = "/:splat/index.html"
  status = 200
