[dev]
  autoLaunch = false

[build]
  # Directory to publish (relative to root of your repo)
  publish = "frontend/dist"
  
  # Default build command
  command = "cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build"

# Function configuration
[functions]
  directory = "backend/dist/netlify/functions"

# Redirects for SPA routing
[[redirects]]
  from = "/scan"
  to = "/.netlify/functions/scan"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200