[build]
  # Directory to publish (relative to root of your repo)
  publish = "public"
  
  # Default build command
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

# Function configuration
[functions]
  directory = "dist/netlify/functions"

# Redirects for SPA routing
[[redirects]]
  from = "/scan"
  to = "/.netlify/functions/scan"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200